### ISSUE TITLE
Vector-conditioning using classifier-free guidance

### ISSUE THREAD

**Issue by jorgejgnz** [tqch/ddpm-torch#1]
I have to implement a conditional diffusion model for synthesizing realistic face images from a feature vector. I found this repo very clarifying. Thank you very much for sharing it!

I made a [fork](https://github.com/jorgejgnz/conditional-ddpm) to support conditional sample generation using [classifier-free guidance](https://arxiv.org/abs/2207.12598). I have been able to successfully generate class-conditioned samples for the MNIST and CIFAR10 datasets. However, I have not been able to generate CELEBA samples using a feature vector as a condition. I was wondering if these models can be adapted to support not only class-conditioning using classifier-free guidance but also vector-conditioning.

I would greatly appreciate any insights you might have on this matter. Thank you in advance for your time and consideration.

**Comment by tqch** [comment]
Hi @jorgejgnz, really nice work on the classifier-free guidance adaptation! I've also done something similar with both single-class label and multiple attributes in my other repo [v-diffusion-torch](https://github.com/tqch/v-diffusion-torch), where I managed to generated human faces conditionally given a **normalized** feature vector. I think the difference between your implementation and mine lies in the conditioning part. I combine temporal embedding and class/tag embedding together before sending them to the residual block while you combine them inside the block through two separate projections. My implementation mainly follows the google-research JAX implementation of [progressive distillation](https://github.com/google-research/google-research/blob/master/ddpm_w_distillation), of which the code is written by the same authors of classifier-free guidance.

**Comment by jorgejgnz** [comment]
I didn't know your other repo and it has helped me. I finally managed to conditionally generate CELEBA samples.
Thank you so much!

**Comment by jorgejgnz** [comment]
I can successfully train the model for CELEBA dataset using a few labels as conditions but the training does not converge on recognizable faces even after 20 epochs when using the 40 labels available for CelebA. I'm not sure if I'm doing something wrong or if the training becomes much more difficult as the number of labels increases .

How many epochs did you need to generate recognizable faces using the 40 CelebA labels?

**Comment by tqch** [comment]
Less than 10 epochs, I would say. The generated images from Epoch 10 look like

![10](https://user-images.githubusercontent.com/61949428/213544344-de69e37b-cacd-4a88-a446-ced71a36eb13.jpg)
