### ISSUE TITLE
DDIM sampler training parameters

### ISSUE THREAD

**Issue by h-bouzid** [tqch/ddpm-torch#10]
Hi, thanks for your great work in implementing the DDPM baseline.
I'm curious about the changes in numberOfSteps, betas start and end, when changing the sampler from DDPM to DDIM. could you please provide me with the DDIM sampler training parameters. 
Thank you in advance.

**Comment by tqch** [comment]
Hi, regarding the parameters for the DDIM sampler, you can refer to the original DDIM [paper](https://arxiv.org/abs/2010.02502). For faster inference speed, I would consider a $S$ of 10 or 20; for better generation quality, I would suggest a $S$ no less than 50. You can specify $S$ by setting the `subseq-size` parameter. 
![image](https://github.com/tqch/ddpm-torch/assets/61949428/80608a16-c78b-47d6-b5c3-c45f9c1dc460)
In terms of time skipping schedule, according to the paper, they recommend the linear schedule for most datasets except for CIFAR10. To do this, simply setting `skip-schedule` as `linear` (or `quadratic`).
![image](https://github.com/tqch/ddpm-torch/assets/61949428/0861ce90-6b4a-4a0d-9b6e-495694a9e366)

**Comment by h-bouzid** [comment]
Thank you very much
