### ISSUE TITLE
what changes would be needed if we want to use our own custom greyscale(channel=1) dataset having size of 256*256.

### ISSUE THREAD

**Issue by awais00012** [tqch/ddpm-torch#15]

**Comment by tqch** [comment]
Hi! You can refer to Issue https://github.com/tqch/ddpm-torch/issues/6 to add your custom image dataset and modify the config file of CelebA-HQ like the following:

1. https://github.com/tqch/ddpm-torch/blob/9879834ed0a3549152b62697ae268c3026698eed/configs/celebahq.json#L2
set `dataset` to your own dataset's name
2. https://github.com/tqch/ddpm-torch/blob/9879834ed0a3549152b62697ae268c3026698eed/configs/celebahq.json#L13
set `in_channels` to 1
