### ISSUE TITLE
Bug in target noise

### ISSUE THREAD

**Issue by rahulvigneswaran** [tqch/ddpm-torch#2]
You are doing `MSE(noise, predicted_noise)`. Shouldn't it be `MSE(coef2*noise, predicted_noise)`?
https://github.com/tqch/ddpm-torch/blob/1bf0e5d178fa374d21f1a0a622bf61fbf3413d29/ddpm_torch/diffusion.py#L235

**Comment by tqch** [comment]
This is not a bug but is intended if you take a look at the pseudo code in the original paper and their official implementation  [link](https://github.com/hojonathanho/diffusion/blob/master/diffusion_tf/diffusion_utils.py#L158).
