### ISSUE TITLE
CIFAR 10 config

### ISSUE THREAD

**Issue by rahulvigneswaran** [tqch/ddpm-torch#3]
Can you provide the exact config you used to get those weights which you linked to?

**Comment by tqch** [comment]
The config files can be found in `./configs` except that:

1. I trained CIFAR-10 model for 2160 epochs (=842.4k iterations) and CelebA model for 600 epochs (=949.2k iterations) in total
2. for both model I used *exponential moving average* (EMA) technique with decay factor 0.9999, which was suggested by the original paper

The checkpoints were not selected based on the FID or anything. I just kept the ones from the last epochs.
