### ISSUE TITLE
Comment in code is wrong. Upsample supports align_corners=True

### ISSUE THREAD

**Issue by Skylion007** [tqch/ddpm-torch#4]
Comment is wrong:
https://github.com/tqch/ddpm-torch/blob/1bf0e5d178fa374d21f1a0a622bf61fbf3413d29/ddpm_torch/models/unet.py#L184

Align_corners=true is now supported by PyTorch. Perhaps the code should be updated?

**Comment by tqch** [comment]
Thanks for reviewing the code! I have double-checked the latest documentation. For the `align_corners` option in `nn.Upsample`, it clearly states that 

> This only has effect when mode is 'linear', 'bilinear', 'bicubic', or 'trilinear'. Default: False

However, here the interpolation mode is 'nearest'.

**Comment by Skylion007** [comment]
Ah you are right. 💯
