### ISSUE TITLE
Meet bugs when adopting the --eval choice for training.

### ISSUE THREAD

**Issue by mo666666** [tqch/ddpm-torch#5]
Hi, tqch! Thank you for your excellent work! However, I found the code can not work well if I select the ``--eval`` arg for training. As I know, maybe there is something wrong with the ``sample_fn`` function. Can you fix this bug? Thank you very much.

**Comment by tqch** [comment]
Hi @mo666666, thanks for the feedback. I have updated the code accordingly in the latest commit [@db49df6](https://github.com/tqch/ddpm-torch/commit/db49df64c19deaa99ac528153f40015251a8f9b6). Still, `--eval` is not recommended if not used together with `--use-ddim`. The reason for that is the default DDPM sampler has to go through 1000 steps, which will inevitably slow down the training process. On the contrary, DDIM sampler with quadratic skip and 50 timesteps is a good option to track the training FIDs approximately at reasonably low time cost.

**Comment by mo666666** [comment]
Thank you for your reply! Your take-away message is quite helpful to me!
