### ISSUE TITLE
Have you tested the FID for CelebaHQ?

### ISSUE THREAD

**Issue by zhuyu-cs** [tqch/ddpm-torch#8]
Hi, thanks for your great work for implementing the DDPM baseline. I'm curious about the FID in CelebaHQ, since I have got 21.64 which may be too higher for DDPM. So if possiable, please let me know the correctness of the above results. Thanks!

**Comment by tqch** [comment]
Thank you for taking the time to verify the CelebA-HQ model checkpoint and report the performance mismatch here! After inspecting the code as well as the released checkpoint, I have identified some potential causes of the performance degradation. I am currently working on addressing these issues and plan to release an update to the repository in the near future.

**Comment by tqch** [comment]
It turned out that the previous CelebA-HQ checkpoint released by this repo was under-trained. I have updated the new checkpoint (1200 epoch model [[link]](https://github.com/tqch/ddpm-torch/releases/download/celeba_hq/celebahq_1200.pt)), whose FID is ~8.9.
